__merge__: ../../api/comp_method.yaml
name: moran_i
label: Moran's I
summary: Moran's I is a measurement of spatial autocorrelation.
description: |
  The MoranI global spatial auto-correlation statistics evaluates whether features (i.e. genes) 
  shows a pattern that is clustered, dispersed or random in the tissue are under consideration.
references: 
  doi: 10.1038/s41592-021-01358-2
info:
  preferred_normalization: counts
links:
  documentation: https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.spatial_autocorr.html
  repository: https://github.com/scverse/squidpy
arguments:
  - name: --coord_type_moran_i
    type: string
    default: generic
    description: Type of coordinate system. Valid options are "grid" for grid coordinates
      or "generic" for generic coordinates.
    choices: [grid, generic]
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - pandas
          - squidpy==1.4.1
          - matplotlib==3.8.3
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
