__merge__: ../../api/comp_method.yaml
name: sepal
label: Sepal
summary: Sepal simulates diffusion of individual transcripts to extract genes with
  spatial patterns.
description: |
  This method assesses the degree of randomness exhibited by each transcript profile and rank them accordingly.
references: 
  doi: 10.1093/bioinformatics/btab164
info:
  preferred_normalization: counts
  documentation_url: https://squidpy.readthedocs.io/en/stable/api/squidpy.gr.sepal.html
  repository_url: https://github.com/scverse/squidpy
arguments:
  - name: --max_neighs_sepal
    type: integer
    default: 6
    description: Maximum number of neighbors of a node in the spatial graph. Valid
      options are 4 (square-grid) and 6 (hexagonal-grid).
    choices: [4, 6]
  - name: --coord_type_sepal
    type: string
    default: grid
    description: Type of coordinate system. Valid options are "grid" for grid coordinates
      or "generic" for generic coordinates.
    choices: [grid, generic]
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - pandas
          - squidpy==1.4.1
          - matplotlib==3.8.3
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
