__merge__: ../../api/comp_metric.yaml
name: correlation
info:
  metrics:
    - name: correlation
      label: correlation
      summary: Correlation represents the agreement of true and predicted spatial
        variability.
      description: |
        Kendall rank correlation coefficient measures the ordinal association between two measured quantities. The best score and upper bound is 1 (observations have an identical rank), while the lower bound is -1 (observations have a completely different rank).
      references: 
        doi: 10.1093/biomet/30.1-2.81
      documentation: https://en.wikipedia.org/wiki/Kendall_rank_correlation_coefficient
      repository: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html
      min: -1
      max: 1
      maximize: true
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: pandas
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
