__merge__: ../../api/comp_method.yaml
name: spagft
label: SpaGFT
summary: SpaGFT is a graph Fourier transform for tissue module identification from spatially resolved transcriptomics
description: |
  The tissue module (TM) was defined as an architectural area containing recurrent cellular 
  communities executing specific biological functions at different tissue sites. 
  However, the computational identification of TMs poses challenges owing to their various 
  length scales, convoluted biological processes, not well-defined molecular features, and 
  irregular spatial patterns. Here, we present a hypothesis-free graph Fourier transform model, 
  SpaGFT, to characterize TMs. For the first time, SpaGFT transforms complex gene expression 
  patterns into simple, but informative signals, leading to the accurate identification of 
  spatially variable genes (SVGs) at a fast computational speed. Based on clustering the 
  transformed signals of the SVGs, SpaGFT provides a novel computational framework for TM 
  characterization. Three case studies were used to illustrate TM identities, the biological 
  processes of convoluted TMs in the lymph node, and conserved TMs across multiple samples constituting 
  the complex organ. The superior accuracy, scalability, and interpretability of SpaGFT indicate 
  that it is a novel and powerful tool for the investigation of TMs to gain new insights into a variety 
  of biological questions.
references: 
  doi: 10.1101/2022.12.10.519929
info:
  preferred_normalization: counts
links:
  documentation: https://spagft.readthedocs.io/en/latest/
  repository: https://github.com/jxLiu-bio/SpaGFT
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: python:3.10
    setup:
      - type: apt
        packages:
          - git
          - procps
          - libhdf5-dev
          - cmake
      - type: docker
        run: |
          git clone https://github.com/jxLiu-bio/SpaGFT.git /opt/SpaGFT
      - type: python
        packages:
          - h5py
          - numba==0.55.1
          - louvain==0.7.1
          - chardet==5.1.0
          - charset-normalizer==3.1.0
          - anndata
          - /opt/SpaGFT
          - mizani==0.9.3
          - pyyaml
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
