__merge__: ../../api/comp_method.yaml
name: spatialde
label: SpatialDE
summary: 'SpatialDE is a method for identify spatially variable genes based on Gaussian Process model'
description: |
  SpatialDE decomposes expression variability into spatial and nonspatial components using two random effect terms: a spatial variance term that parametrizes gene expression covariance by pairwise distances of samples, and a noise term that models nonspatial variability.
references: 
  doi: 10.1038/nmeth.4636
info:
  preferred_normalization: counts
links:
  documentation: https://github.com/Teichlab/SpatialDE
  repository: https://github.com/Teichlab/SpatialDE
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: apt
        packages: git
      - type: docker
        run: |
          git clone https://github.com/Teichlab/SpatialDE.git /opt/SpatialDE
      - type: python
        packages:
          - /opt/SpatialDE/Python-module
          - scanpy==1.9.8
          - pandas==2.2.1
          - numpy==1.26.4
          - scipy==1.11.4
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [hightime, highmem, midcpu]
