name: select_reference
namespace: data_processors
description: Compute SVG
info:
  type: data_processor
  type_info:
    label: Select reference
    description: |
      Computes the spatially variable genes scores and select certain number of SVGs as reference.
arguments:
  - name: --input
    __merge__: ../../api/file_common_dataset.yaml
    required: true
    direction: input
  - name: --input_layer
    type: string
    default: normalized
    description: Which layer to use as input.
  - name: --output
    type: file
    direction: output
    required: true
    __merge__: ../../api/file_common_dataset.yaml
  - name: --coord_type_proc
    type: string
    default: grid
    description: How to create spatial graph to select reference genes.
    choices: [grid, generic]
  - name: --num_features
    type: integer
    default: 200
    description: The number of variable genes to select
resources:
  - type: python_script
    path: script.py
test_resources:
  - path: /resources_test/common/mouse_brain_coronal_section1
    dest: resources_test/common/mouse_brain_coronal_section1
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages:
          - squidpy
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, midcpu]
