name: "spatialde2"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_data"
    label: "Dataset"
    summary: "The dataset without spatially variable genes."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts."
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalised expression values"
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, in this case a ENSEMBL\
            \ gene id suffixed with alpha value."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, in this case a gene\
            \ symbol suffixed with alpha value."
          required: false
        obsm:
        - type: "double"
          name: "spatial"
          description: "Spatial coordinates for each spot."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: false
    example:
    - "resources_test/spatially_variable_genes/mouse_brain_coronal_section1/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Output"
    summary: "Anndata with estimate spatial variability."
    description: "Anndata with estimated spatial variability score for each gene."
    info:
      format:
        type: "h5ad"
        var:
        - type: "string"
          name: "feature_id"
          description: "Feature ID"
          required: true
        - type: "string"
          name: "feature_name"
          description: "Feature name"
          required: false
        - type: "double"
          name: "pred_spatial_var_score"
          description: "Predicted spatial variability score"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
    example:
    - "resources_test/spatially_variable_genes/mouse_brain_coronal_section1/output.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "SpatialDE2"
summary: "SpatialDE2: Fast and localized variance component analysis of spatial transcriptomics"
description: "Spatial transcriptomics is now a mature technology, allowing to assay\
  \ gene expression changes \nin the histological context of complex tissues. A canonical\
  \ analysis workflow starts with the \nidentification of tissue zones that share\
  \ similar expression profiles, followed by the detection \nof highly variable or\
  \ spatially variable genes. Rapid increases in the scale and complexity of \nspatial\
  \ transcriptomic datasets demand that these analysis steps are conducted in a consistent\
  \ \nand integrated manner, a requirement that is not met by current methods. To\
  \ address this, we \nhere present SpatialDE2, which unifies the mapping of tissue\
  \ zones and spatial variable gene \ndetection as integrated software framework,\
  \ while at the same time advancing current algorithms \nfor both of these steps.\
  \ Formulated in a Bayesian framework, the model accounts for the Poisson \ncount\
  \ noise, while simultaneously offering superior computational speed compared to\
  \ previous methods. \nWe validate SpatialDE2 using simulated data and illustrate\
  \ its utility in the context of two real-world \napplications to the spatial transcriptomics\
  \ profiles of the mouse brain and human endometrium.\n"
test_resources:
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "file"
  path: "resources_test/spatially_variable_genes/mouse_brain_coronal_section1"
  dest: "resources_test/spatially_variable_genes/mouse_brain_coronal_section1"
- type: "file"
  path: "library.bib"
info:
  preferred_normalization: "counts"
  documentation_url: "https://pmbio.github.io/SpatialDE/"
  repository_url: "https://github.com/PMBio/SpatialDE"
  type: "method"
  type_info:
    label: "Method"
    summary: "A spatially variable gene identification method."
    description: "Method to identify spatially variable genes"
status: "enabled"
repositories:
- type: "github"
  name: "openproblems-v2"
  repo: "openproblems-bio/openproblems-v2"
  tag: "main_build"
license: "MIT"
references:
  doi:
  - "10.1101/2021.10.27.466045"
links:
  repository: "https://github.com/openproblems-bio/task_spatially_variable_genes"
  docker_registry: "ghcr.io"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    - "gpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "apt"
    packages:
    - "libhdf5-dev"
    - "cmake"
    interactive: false
  - type: "docker"
    run:
    - "git clone https://github.com/PMBio/SpatialDE.git /opt/SpatialDE2\n"
  - type: "python"
    user: false
    packages:
    - "patsy"
    - "/opt/SpatialDE2"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/spatialde2/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/methods/spatialde2"
  executable: "target/nextflow/methods/spatialde2/main.nf"
  viash_version: "0.9.0-RC7"
  git_commit: "a2a2f7f4d4ace9466aabeef469f088b6050468a7"
  git_remote: "https://github.com/openproblems-bio/task_spatially_variable_genes"
package_config:
  name: "task_spatially_variable_genes"
  version: "build_main"
  label: "Spatially Variable Genes"
  summary: "Spatially variable genes (SVGs) are genes whose expression levels vary\
    \ significantly across different spatial regions within a tissue or across cells\
    \ in a spatially structured context."
  description: "Recent years have witnessed significant progress in spatially-resolved\
    \ transcriptome profiling techniques that simultaneously characterize cellular\
    \ gene expression and their physical position, generating spatial transcriptomic\
    \ (ST) data. The application of these techniques has dramatically advanced our\
    \ understanding of disease and developmental biology. One common task for all\
    \ ST profiles, regardless of the employed protocols, is to identify genes that\
    \ exhibit spatial patterns. These genes, defined as spatially variable genes (SVGs),\
    \ contain additional information about the spatial structure of the tissues of\
    \ interest, compared to highly variable genes (HVGs).\n\nIdentification of spatially\
    \ variable genes is crucial to for studying spatial domains within tissue microenvironmnets,\
    \ developmental gradients and cell signaling pathways. In this task we attempt\
    \ to evaluate various methods for detecting SVGs using a number of realistic simulated\
    \ datasets with diverse patterns derived from real-world spatial transcriptomics\
    \ data using scDesign3. Synthetic data is generated by mixing a Gaussian Process\
    \ (GP) model and a non-spatial model (obtained by shuffling mean parameters of\
    \ the GP model to remove spatial correlation between spots) to generate gene expressions\
    \ with various spatial variability. For more details, please refer to our [manuscript](https://www.biorxiv.org/content/10.1101/2023.12.02.569717v1)\
    \ and [Github](https://github.com/pinellolab/SVG_Benchmarking).\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/spatially_variable_genes/"
      dest: "resources_test/spatially_variable_genes"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "openproblems-v2"
    repo: "openproblems-bio/openproblems-v2"
    tag: "main_build"
  viash_version: "0.9.0-RC7"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n.runners[.type == \"nextflow\"].config.script := \"process.errorStrategy\
    \ = 'ignore'\"\n"
  authors:
  - name: "Zhijian Li"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "lzj1769"
      orcid: "0000-0002-1523-1333"
  - name: "Zain M. Patel"
    roles:
    - "author"
    info:
      github: "doczmp"
  - name: "Dongyuan Song"
    roles:
    - "author"
    info:
      github: "SONGDONGYUAN1994"
  - name: "Guanao Yan"
    roles:
    - "author"
    info: null
  - name: "Jingyi Jessica Li"
    roles:
    - "author"
    info:
      github: "JSB-UCLA"
  - name: "Luca Pinello"
    roles:
    - "author"
    info:
      github: "pinellolab"
  - name: "Robrecht Cannoodt"
    roles:
    - "contributor"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  - "spatial"
  - "transcriptomics"
  - "spatial variablility"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.1101/2023.12.02.569717"
  links:
    repository: "https://github.com/openproblems-bio/task_spatially_variable_genes"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_spatially_variable_genes/issues"
