__merge__: ../../api/comp_method.yaml
name: spatialde2
label: SpatialDE2
summary: 'SpatialDE2: Fast and localized variance component analysis of spatial transcriptomics'
description: |
  Spatial transcriptomics is now a mature technology, allowing to assay gene expression changes 
  in the histological context of complex tissues. A canonical analysis workflow starts with the 
  identification of tissue zones that share similar expression profiles, followed by the detection 
  of highly variable or spatially variable genes. Rapid increases in the scale and complexity of 
  spatial transcriptomic datasets demand that these analysis steps are conducted in a consistent 
  and integrated manner, a requirement that is not met by current methods. To address this, we 
  here present SpatialDE2, which unifies the mapping of tissue zones and spatial variable gene 
  detection as integrated software framework, while at the same time advancing current algorithms 
  for both of these steps. Formulated in a Bayesian framework, the model accounts for the Poisson 
  count noise, while simultaneously offering superior computational speed compared to previous methods. 
  We validate SpatialDE2 using simulated data and illustrate its utility in the context of two real-world 
  applications to the spatial transcriptomics profiles of the mouse brain and human endometrium.
references: 
  doi: 10.1101/2021.10.27.466045
info:
  preferred_normalization: counts
links:
  documentation: https://pmbio.github.io/SpatialDE/
  repository: https://github.com/PMBio/SpatialDE
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: apt
        packages:
          - libhdf5-dev
          - cmake
      - type: docker
        run: |
          git clone https://github.com/PMBio/SpatialDE.git /opt/SpatialDE2
      - type: python
        packages:
          - patsy
          - /opt/SpatialDE2
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu, gpu]
