__merge__: ../../api/comp_method.yaml
name: boostgp
label: BOOST-GP
summary: Bayesian modeling of spatial molecular profiling data via Gaussian process
description: |
  BOOST-GP a novel Bayesian hierarchical model to analyze spatial transcriptomics data, 
  with several unique characteristics. It models the zero-inflated and over-dispersed 
  counts by deploying a zero-inflated negative binomial model that greatly increases 
  model stability and robustness. Besides, the Bayesian inference framework allows us 
  to borrow strength in parameter estimation in a de novo fashion. As a result, 
  the proposed model shows competitive performances in accuracy and robustness 
  over existing methods in both simulation studies and two real data applications.
references: 
  doi: 10.1093/bioinformatics/btab455
info:
  preferred_normalization: counts
  documentation_url: https://github.com/Minzhe/BOOST-GP
  repository_url: https://github.com/Minzhe/BOOST-GP
arguments:
  - name: --n_iter
    type: integer
    description: Number of iterations.
    default: 10
    info:
      test_default: 7
resources:
  - type: r_script
    path: script.R
engines:
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: apt
        packages:
          - git
      - type: docker
        run: |
          git clone https://github.com/Minzhe/BOOST-GP.git /opt/BOOST-GP
      - type: r
        cran: [RcppDist, ggplot2, anndata]
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [veryhightime, midmem, midcpu]
