__merge__: ../../api/comp_method.yaml
name: gpcounts
label: GPcounts
summary: GPcounts is non-parametric modelling of temporal and spatial counts data
  from RNA-seq experiments.
description: |
  The GPcounts package implements GP regression methods for modelling counts data using a 
  negative binomial likelihood function. Computational efficiency is achieved through the use of 
  variational Bayesian inference. The GP function models changes in the mean of the negative binomial 
  likelihood through a logarithmic link function and the dispersion parameter is fitted by maximum 
  likelihood. We validate the method on simulated time course data, showing better performance to identify 
  changes in over-dispersed counts data than methods based on Gaussian or Poisson likelihoods. 
references: 
  doi: 10.1093/bioinformatics/btab486
info:
  preferred_normalization: counts
  documentation_url: 
    https://github.com/ManchesterBioinference/GPcounts/blob/master/demo_notebooks/GPcounts_spatial.ipynb
  repository_url: https://github.com/ManchesterBioinference/GPcounts
arguments:
  - name: --n_features
    type: integer
    description: Number of features to include.
    info:
      test_default: 120
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_tensorflow_nvidia:1.0.0
    setup:
      - type: apt
        packages:
          - git
      - type: python
        packages:
          - tensorflow-probability
          - tensorflow[and-cuda]
          - gpflow
          - scipy==1.9.1
      - type: docker
        run: |
          git clone https://github.com/markvdw/RobustGP.git /opt/RobustGP && \
          git clone https://github.com/lzj1769/GPcounts.git /opt/GPcounts
      - type: python
        packages:
          - /opt/RobustGP
          - /opt/GPcounts
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [veryhightime, midmem, midcpu, gpu]
