name: "scgco"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_data"
    label: "Dataset"
    summary: "The dataset without spatially variable genes."
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts."
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalised expression values"
          required: true
        var:
        - type: "string"
          name: "feature_id"
          description: "Unique identifier for the feature, in this case a ENSEMBL\
            \ gene id suffixed with alpha value."
          required: false
        - type: "string"
          name: "feature_name"
          description: "A human-readable name for the feature, in this case a gene\
            \ symbol suffixed with alpha value."
          required: false
        obsm:
        - type: "double"
          name: "spatial"
          description: "Spatial coordinates for each spot."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - name: "dataset_name"
          type: "string"
          description: "Nicely formatted name."
          required: false
    example:
    - "resources_test/spatially_variable_genes/mouse_brain_coronal_section1/dataset.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Output"
    summary: "Anndata with estimate spatial variability."
    description: "Anndata with estimated spatial variability score for each gene."
    info:
      format:
        type: "h5ad"
        var:
        - type: "string"
          name: "feature_id"
          description: "Feature ID"
          required: true
        - type: "string"
          name: "feature_name"
          description: "Feature name"
          required: false
        - type: "double"
          name: "pred_spatial_var_score"
          description: "Predicted spatial variability score"
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
    example:
    - "resources_test/spatially_variable_genes/mouse_brain_coronal_section1/output.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "scGCO"
summary: "Identification of spatially variable genes with graph cuts."
description: "Single-cell gene expression data with positional information is critical\
  \ to dissect \nmechanisms and architectures of multicellular organisms, but the\
  \ potential is limited \nby the scalability of current data analysis strategies.\
  \ Here, we present scGCO, \na method based on fast optimization of hidden Markov\
  \ Random Fields with graph cuts \nto identify spatially variable genes. Comparing\
  \ to existing methods, scGCO delivers \na superior performance with lower false\
  \ positive rate and improved specificity, \nwhile demonstrates a more robust performance\
  \ in the presence of noises. \nCritically, scGCO scales near linearly with inputs\
  \ and demonstrates orders of \nmagnitude better running time and memory requirement\
  \ than existing methods, \nand could represent a valuable solution when spatial\
  \ transcriptomics data grows \ninto millions of data points and beyond..\n"
test_resources:
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "file"
  path: "resources_test/spatially_variable_genes/mouse_brain_coronal_section1"
  dest: "resources_test/spatially_variable_genes/mouse_brain_coronal_section1"
- type: "file"
  path: "library.bib"
info:
  preferred_normalization: "counts"
  type: "method"
  type_info:
    label: "Method"
    summary: "A spatially variable gene identification method."
    description: "Method to identify spatially variable genes"
status: "enabled"
repositories:
- type: "github"
  name: "core"
  repo: "openproblems-bio/core"
  tag: "build/main"
  path: "viash/core"
- type: "github"
  name: "openproblems"
  repo: "openproblems-bio/openproblems"
  tag: "main_build"
license: "MIT"
references:
  doi:
  - "10.1038/s41467-022-33182-3"
links:
  repository: "https://github.com/WangPeng-Lab/scGCO"
  docker_registry: "ghcr.io"
  documentation: "https://github.com/WangPeng-Lab/scGCO/blob/master/code/Tutorial/scGCO_tutorial.ipynb"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "midcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
    script:
    - "process.errorStrategy = 'ignore'"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "python:3.9.16"
  namespace_separator: "/"
  setup:
  - type: "apt"
    packages:
    - "git"
    - "procps"
    - "libhdf5-dev"
    - "cmake"
    - "gdal-bin"
    - "libgdal-dev"
    interactive: false
  - type: "docker"
    run:
    - "pip install Cython==0.29.33 numpy==1.23.5 scipy==1.9.1 && \\\ngit clone https://github.com/lzj1769/scGCO_simple.git\
      \ /opt/scGCO/scGCO_simple && \\\n"
  - type: "python"
    user: false
    github:
    - "openproblems-bio/core#subdirectory=packages/python/openproblems"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "h5py==3.8.0"
    - "pandas==1.5.3"
    - "parmap==1.6.0"
    - "scanpy==1.9.3"
    - "tqdm==4.65.0"
    - "anndata==0.8.0"
    - "matplotlib==3.7.1"
    - "scikit-learn==1.2.2"
    - "hdbscan"
    - "seaborn==0.12.2"
    - "pysal==2.0.0"
    - "pygco==0.0.16"
    - "shapely==2.0.1"
    - "networkx==2.5"
    - "scikit-image"
    - "pyyaml"
    - "requests"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/scgco/config.vsh.yaml"
  runner: "nextflow"
  engine: "docker"
  output: "target/nextflow/methods/scgco"
  executable: "target/nextflow/methods/scgco/main.nf"
  viash_version: "0.9.0"
  git_commit: "1ad99b58115350e06df66d5a0d6ede7834095e02"
  git_remote: "https://github.com/openproblems-bio/task_spatially_variable_genes"
package_config:
  name: "task_spatially_variable_genes"
  version: "build_main"
  label: "Spatially Variable Genes"
  summary: "Spatially variable genes (SVGs) are genes whose expression levels vary\
    \ significantly across different spatial regions within a tissue or across cells\
    \ in a spatially structured context."
  description: "Recent years have witnessed significant progress in spatially-resolved\
    \ transcriptome profiling techniques that simultaneously characterize cellular\
    \ gene expression and their physical position, generating spatial transcriptomic\
    \ (ST) data. The application of these techniques has dramatically advanced our\
    \ understanding of disease and developmental biology. One common task for all\
    \ ST profiles, regardless of the employed protocols, is to identify genes that\
    \ exhibit spatial patterns. These genes, defined as spatially variable genes (SVGs),\
    \ contain additional information about the spatial structure of the tissues of\
    \ interest, compared to highly variable genes (HVGs).\n\nIdentification of spatially\
    \ variable genes is crucial to for studying spatial domains within tissue microenvironmnets,\
    \ developmental gradients and cell signaling pathways. In this task we attempt\
    \ to evaluate various methods for detecting SVGs using a number of realistic simulated\
    \ datasets with diverse patterns derived from real-world spatial transcriptomics\
    \ data using scDesign3. Synthetic data is generated by mixing a Gaussian Process\
    \ (GP) model and a non-spatial model (obtained by shuffling mean parameters of\
    \ the GP model to remove spatial correlation between spots) to generate gene expressions\
    \ with various spatial variability. For more details, please refer to our [manuscript](https://www.biorxiv.org/content/10.1101/2023.12.02.569717v1)\
    \ and [Github](https://github.com/pinellolab/SVG_Benchmarking).\n"
  info:
    image: "thumbnail.svg"
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/spatially_variable_genes/"
      dest: "resources_test/spatially_variable_genes"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "core"
    repo: "openproblems-bio/core"
    tag: "build/main"
    path: "viash/core"
  - type: "github"
    name: "openproblems"
    repo: "openproblems-bio/openproblems"
    tag: "main_build"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n.runners[.type == \"nextflow\"].config.script := \"process.errorStrategy\
    \ = 'ignore'\"\n"
  authors:
  - name: "Zhijian Li"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "lzj1769"
      orcid: "0000-0002-1523-1333"
  - name: "Zain M. Patel"
    roles:
    - "author"
    info:
      github: "doczmp"
  - name: "Dongyuan Song"
    roles:
    - "author"
    info:
      github: "SONGDONGYUAN1994"
  - name: "Guanao Yan"
    roles:
    - "author"
    info: null
  - name: "Jingyi Jessica Li"
    roles:
    - "author"
    info:
      github: "JSB-UCLA"
  - name: "Luca Pinello"
    roles:
    - "author"
    info:
      github: "pinellolab"
  - name: "Robrecht Cannoodt"
    roles:
    - "contributor"
    info:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Sai Nirmayi Yasa"
    roles:
    - "contributor"
    info:
      github: "sainirmayi"
      orcid: "0009-0003-6319-9803"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  - "spatial"
  - "transcriptomics"
  - "spatial variablility"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.1101/2023.12.02.569717"
  links:
    repository: "https://github.com/openproblems-bio/task_spatially_variable_genes"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_spatially_variable_genes/issues"
