name: process_datasets
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        __merge__: /src/api/file_common_dataset.yaml
        description: "Input dataset"
        required: true
  - name: Outputs
    arguments:
      - name: "--output_dataset"
        __merge__: /src/api/file_dataset.yaml
        required: true
        direction: output
      - name: "--output_solution"
        __merge__: /src/api/file_solution.yaml
        required: true
        direction: output
      - name: "--dataset_simulated_normalized"
        __merge__: /src/api/file_simulated_dataset.yaml
        required: false
        direction: output
  - name: Simulation options
    arguments:
      - type: integer
        name: --gp_k_sim
        description: Dimension of basis used for the Gaussian process smoother.
        default: 500
        info:
          test_value: 50
      - type: integer
        name: --select_top_variable_genes_sim
        description: Number of top variable genes to use for subsetting.
        default: 50
  - name: Reference genes
    arguments: 
      - name: "--num_reference_genes"
        type: integer
        description: Number of top SVGs to select as reference.
        default: 200
      - name: "--coord_type_proc"
        type: string
        default: "grid"
        description: "How to create spatial graph to select reference genes."
        choices: [grid, generic]
  - name: Normalization options
    arguments: 
      - name: "--n_cp"
        type: integer
        default: -1
        description: "Number of counts per cell. When set to -1, will use None."

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: schema/verify_data_structure
    repository: core
  - name: dataset_processors/select_reference
  - name: dataset_processors/simulate_svg
  - name: datasets/normalization/log_cp
    repository: openproblems
  - name: dataset_processors/split_dataset

runners:
  - type: nextflow
