__merge__: ../../api/comp_control_method.yaml
name: random_ranking
label: Random Ranking
summary: Negative control method that randomly rank genes.
description: |
  A negative control method with random ranking of genes.
info:
  preferred_normalization: counts
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: pandas
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
