name: split_dataset
namespace: data_processors
info:
  type: data_processor
  type_info:
    label: Split dataset
    summary: A spatially variable genes dataset processor.
    description: |
      Split the common dataset for the spatially_variable_genes task.
arguments:
  - name: --input
    __merge__: ../../api/file_simulated_dataset.yaml
    direction: input
    required: true
  - name: --output_dataset
    __merge__: ../../api/file_dataset.yaml
    direction: output
    required: true
  - name: --output_solution
    __merge__: ../../api/file_solution.yaml
    direction: output
    required: true
resources:
  - type: python_script
    path: script.py
  - path: /common/helper_functions/subset_h5ad_by_format.py
test_resources:
  - type: python_script
    path: /common/component_tests/run_and_check_output.py
  - path: /resources_test/spatially_variable_genes/mouse_brain_coronal_section1
    dest: resources_test/spatially_variable_genes/mouse_brain_coronal_section1
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, highmem, highcpu]
