__merge__: ../../api/comp_control_method.yaml
name: true_ranking
label: True Ranking
summary: Positive control method that correctly rank genes.
description: |
  A positive control method with correct ranking of genes.
info:
  preferred_normalization: counts
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: openproblems/base_python:1.0.0
    setup:
      - type: python
        packages: pandas
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime, midmem, midcpu]
